export enum RoutesEnum {
  SignIn = '/',
  SignUp = '/sign-up',
  Profile = '/profile',
  ProfileChange = '/profile-change',
  Password = '/password',
  Forums = '/forum',
  Thread = ':thread',
  CreateThread = 'createThread',
  ServerError = '/server-error',
  NotFound = '*',
  Game = '/game',
  Leaderboard = '/leaderboard',
  Example = '/example',
}
